# Generated by Django 4.1.4 on 2022-12-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenca',
            name='orgao',
            field=models.IntegerField(choices=[(2, 'Semarh'), (3, 'Ima'), (4, 'Ibama'), (5, 'Corpo De Bombeiros')], null=True),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='arquivo_licenca',
            field=models.FileField(blank=True, upload_to='licencas'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='observacao',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
