# Generated by Django 4.1.4 on 2022-12-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0002_licenca_orgao_alter_licenca_arquivo_licenca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionante',
            name='frquencia_entrega',
            field=models.IntegerField(blank=True, choices=[(1, 'Mensal'), (2, 'Bimestral'), (3, 'Trimestral'), (4, 'Semestral'), (5, 'Anual')], null=True),
        ),
        migrations.AlterField(
            model_name='condicionante',
            name='descricao',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='orgao',
            field=models.IntegerField(choices=[(1, 'Sedet'), (2, 'Semarh'), (3, 'Ima'), (4, 'Ibama'), (5, 'Corpo De Bombeiros')], null=True),
        ),
    ]
