# Generated by Django 4.1.4 on 2022-12-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0003_condicionante_frquencia_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenca',
            name='status_renovacao',
            field=models.IntegerField(choices=[(1, 'Em Andamento'), (2, 'Necessario Iniciar'), (3, 'Nao Precisa'), (4, 'Licenca Em Dia')], null=True),
        ),
    ]
